version: 2.1

jobs:
  build-glibc:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout

      - run: |
          docker run -it --rm -v "$PWD":/work -w /work golang:1.19-bullseye bash -c 'go build -ldflags="-s -w"'
          sudo mv go-transcode go-transcode-aarch64-glibc

      - persist_to_workspace:
          root: .
          paths:
            - go-transcode-aarch64-glibc

  build-musl:
    machine:
      image: ubuntu-2004:current
    resource_class: arm.medium
    steps:
      - checkout

      - run: |
          docker run -it --rm -v "$PWD":/work -w /work golang:1.19-alpine sh -c 'go build -ldflags="-s -w"'
          mv go-transcode go-transcode-aarch64-musl

      - persist_to_workspace:
          root: .
          paths:
            - go-transcode-aarch64-musl

  publish-github-release:
    docker:
      - image: cimg/go:1.17
    steps:
      - attach_workspace:
          at: ./artifacts
      - run:
          name: "Publish Release on GitHub"
          command: |
            go get github.com/tcnksm/ghr
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} -replace ${CIRCLE_TAG} ./artifacts/

workflows:
  aarch64-glibc:
    jobs:
      - build-glibc:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.*/
      - publish-github-release:
          requires:
            - build-glibc
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /^.*/

  aarch64-musl:
    jobs:
      - build-musl:
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
      - publish-github-release:
          requires:
            - build-musl
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/